site_name: beapkgs
docs_dir: ./docs
site_url: https://isabelroses.github.io/beapkgs/
repo_url: https://github.com/isabelroses/beapkgs
repo_name: isabelroses/beapkgs
site_description: beapkgs documentation
site_author: isabel roses
copyright: Licenced MIT
theme:
  name: material
  features:
    - content.tooltips
    - search.highlight
    - navigation.tabs
    - navigation.indexes
    - navigation.prune
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Light Mode
plugins:
  - search
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
