[nh-darwin]
src.git = "https://github.com/ToyVo/nh_darwin"
fetch.github = "ToyVo/nh_darwin"
cargo_locks = ["Cargo.lock"]

[bellado]
src.git = "https://github.com/isabelroses/bellado"
fetch.github = "isabelroses/bellado"

[blahaj]
src.git = "https://github.com/isabelroses/blahaj"
fetch.github = "isabelroses/blahaj"
cargo_locks = ["Cargo.lock"]

[izrss]
src.git = "https://github.com/isabelroses/izrss"
fetch.github = "isabelroses/izrss"

[ringfairy]
src.git = "https://github.com/k3rs3d/ringfairy"
fetch.github = "k3rs3d/ringfairy"
cargo_locks = ["Cargo.lock"]

[purr]
src.git = "https://github.com/uncenter/purr"
fetch.github = "uncenter/purr"
cargo_locks = ["Cargo.lock"]

[nixpkgs-using]
src.git = "https://github.com/uncenter/nixpkgs-using"
fetch.github = "uncenter/nixpkgs-using"
cargo_locks = ["Cargo.lock"]

[nixpkgs-track]
src.git = "https://github.com/uncenter/nixpkgs-track"
fetch.github = "uncenter/nixpkgs-track"
cargo_locks = ["Cargo.lock"]

[ito]
src.git = "https://github.com/uncenter/ito"
fetch.github = "uncenter/ito"
cargo_locks = ["Cargo.lock"]

[meower]
src.git = "https://github.com/Noxyntious/meower"
fetch.github = "Noxyntious/meower"
cargo_locks = ["Cargo.lock"]

[isabelroses-website]
src.git = "https://github.com/isabelroses/website"
fetch.github = "isabelroses/website"
cargo_locks = ["Cargo.lock"]

[hael]
src.git = "https://github.com/isabelroses/hael"
fetch.github = "isabelroses/hael"

[hyfetch]
src.git = "https://github.com/hykilpikonna/hyfetch"
fetch.github = "hykilpikonna/hyfetch"
cargo_locks = ["Cargo.lock"]

[zzz]
src.git = "https://github.com/isabelroses/zzz"
fetch.github = "isabelroses/zzz"

[wezterm]
src.git = "https://github.com/wez/wezterm"
fetch.github = "wez/wezterm"
git.fetchSubmodules = true
cargo_locks = ["Cargo.lock"]

# broken somehow
# [term2alpha]
# src.git = "https://sr.ht/~zethra/term2alpha"
# fetch.git = "https://sr.ht/~zethra/term2alpha"

# gonvim-tools
[go-enum]
fetch.github = "abice/go-enum"
src.github = "abice/go-enum"

[gomvp]
fetch.github = "abenz1267/gomvp"
src.git = "https://github.com/abenz1267/gomvp"

[json-to-struct]
fetch.github = "tmc/json-to-struct"
src.git = "https://github.com/tmc/json-to-struct"

# LSPs
[helm-ls]
fetch.github = "mrjosh/helm-ls"
src.github = "mrjosh/helm-ls"

[jq-lsp]
fetch.github = "wader/jq-lsp"
src.git = "https://github.com/wader/jq-lsp"
