name: Build and populate cache

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
    paths:
      - "flake/pkgs"
      - "**.lock"
      - "_sources/*"
      - ".github/workflows/build.yml"

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          logger: pretty

      - name: Generate matrix
        id: gen-matrix
        run: |
          set -Eeu
          matrix="$(nix eval --json '.#githubActions.matrix')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  build:
    name: ${{ matrix.name }} (${{ matrix.system }})

    needs: setup
    strategy:
      matrix: ${{fromJSON(needs.setup.outputs.matrix)}}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          logger: pretty

      - name: Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Setup cachix
        uses: cachix/cachix-action@v15
        with:
          name: isabelroses
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_TOKEN }}"

      - name: Build from the matrix
        run: |
          export NIXPKGS_ALLOW_UNFREE=1
          nix build -L .#${{ matrix.package }} --impure
