name: Build and populate cache

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
    paths:
      - "flake/pkgs"
      - "**.lock"
      - "_sources/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          source_url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          logger: pretty

      - name: build
        run: nix run nixpkgs#nix-fast-build -- --no-nom
