name: Bump Flake Inputs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    if: github.repository == 'isabelroses/beapkgs'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          source_url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          logger: pretty

      - name: Update Lockfile
        run: nix flake update

      - name: Update nvfetcher
        run: nix run nixpkgs#nvfetcher

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update"
          push_options: "--force"
          commit_user_name: GitHub Actions

